### ISSUE TITLE
Insufficient instructions?

### ISSUE THREAD

**Issue by akbr** [olistic/warriorjs-engine#5]
Some in-game instructions seem incomplete. For example, the instructions for level 8 (beginner):

> Use `warrior.look()` to determine your surroundings, and `warrior.shoot()` to fire an arrow.

How should the user know that `warrior.look()` returns an array (without looking at the game's [source code](https://github.com/olistic/warriorjs-engine/blob/master/src/abilities/senses/Look.js#L9))?

A more detailed API reference would help. Alternatively, what about letting the user log data when running their script?

**Comment by akbr** [comment]
Realized this is related to the web frontend, and not the guts.

**Comment by olistic** [comment]
Yeah, the web version is still work in progress and one of the remaining items is adding the list of abilities your warrior currently has with a detailed explanation. In the meantime, you can find it [here](https://github.com/olistic/warriorjs/blob/master/README.md#abilities).
